language: node_js
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/waiter_tests

node_js:
  - "v8.10.0"

services:
  - postgresql

before_script:
  - psql -c 'create database  waiter_tests;' -U postgres
  - psql -U postgres -d waiter_tests -a -f waiters.sql

addons:
  apt:
    packages:
      - postgresql-server-dev-9.2